services:
  qc.fair_bluesy-harlequin-tarsier:
    image: steinsteiny/fuji:fair
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
